server:
  port: 8081
spring:
  application:
    name: discovery-provider
  cloud:
    nacos:
      discovery:
        server-addr: 172.26.3.174:8848
management:
  endpoints:
    web:
      exposure:
        include: "*"